---
- name: Move and link configs for RedHat family
  block:
    - name: Move configs for Apache and Nginx (RedHat)
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: yes
      loop:
        - { src: './configs/wordpress', dest: '/etc/httpd/conf.d/' }
        - { src: './configs/wordpress.conf', dest: '/etc/nginx/conf.d/' }
        - { src: './configs/joomla', dest: '/etc/httpd/conf.d/' }
        - { src: './configs/joomla.conf', dest: '/etc/nginx/conf.d/' }
      register: move_result

    - name: Show success message after moving configs for Apache and Nginx (RedHat)
      ansible.builtin.debug:
        msg: "Configs have been successfully moved for RedHat."
      when: move_result.changed

    - name: Remove configs directory
      file:
        path: "./configs"
        state: absent
      register: remove_result

    - name: Show success message after removing configs directory
      ansible.builtin.debug:
        msg: "The configs directory has been successfully removed."
      when: remove_result.changed
  notify:
    - Restart httpd
