---
- name: Install PHP and extensions
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-fpm
    - php-mysqli
  register: php_installation

- name: Show success message after installing PHP and extensions
  ansible.builtin.debug:
    msg: "PHP and extensions have been successfully installed on {{ ansible_distribution }}"
  when: 
    - php_installation is changed