---
- name: Install required software
  dnf:
    name:
      - wget
      - git
    state: present
  register: requiredSoftware

- name: Show success message after installing requiredSoftware
  ansible.builtin.debug:
    msg: "requiredSoftware has been successfully installed"
  when: requiredSoftware is changed